name: 📦 Deploy Application

on:
  workflow_run:
    workflows: ["🐋 Build Docker Image"]
    branches: 
      - main
    types: 
      - completed
  
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploying docker compose
      uses: appleboy/ssh-action@v1.0.0
      env:
        DIRECTORY: ${{ secrets.DIRECTORY }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        envs: DIRECTORY
        script: |
          cd $DIRECTORY
          docker compose pull
          docker compose up --no-deps -d api